//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIIS.CarManager.DbWebSvc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbWebSvc.DbWebSvcSoap")]
    public interface DbWebSvcSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromSql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataFromSql(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataFromSql", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataFromSqlAsync(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteSql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ExecuteSql(string strSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteSql", ReplyAction="*")]
        System.Threading.Tasks.Task ExecuteSqlAsync(string strSql);
        
        // CODEGEN: 参数“ParameterBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RIIS.CarManager.DbWebSvc.InsertWithParamResponse InsertWithParam(RIIS.CarManager.DbWebSvc.InsertWithParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithParam", ReplyAction="*")]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.InsertWithParamResponse> InsertWithParamAsync(RIIS.CarManager.DbWebSvc.InsertWithParamRequest request);
        
        // CODEGEN: 参数“ParameterBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RIIS.CarManager.DbWebSvc.UpdateWithParamResponse UpdateWithParam(RIIS.CarManager.DbWebSvc.UpdateWithParamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithParam", ReplyAction="*")]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParamResponse> UpdateWithParamAsync(RIIS.CarManager.DbWebSvc.UpdateWithParamRequest request);
        
        // CODEGEN: 参数“ParameterBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithParam_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response UpdateWithParam_2(RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithParam_2", ReplyAction="*")]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response> UpdateWithParam_2Async(RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request request);
        
        // CODEGEN: 参数“ParameterBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteStoredProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse ExecuteStoredProcedure(RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteStoredProcedure", ReplyAction="*")]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse> ExecuteStoredProcedureAsync(RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataTables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataTables(string[] tableNameList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataTables", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataTablesAsync(string[] tableNameList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteBatchSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ExecuteBatchSQL(string[] sqlArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteBatchSQL", ReplyAction="*")]
        System.Threading.Tasks.Task ExecuteBatchSQLAsync(string[] sqlArr);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertWithParam", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertWithParamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ParameterBytes;
        
        public InsertWithParamRequest() {
        }
        
        public InsertWithParamRequest(string tableName, byte[] ParameterBytes) {
            this.tableName = tableName;
            this.ParameterBytes = ParameterBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertWithParamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertWithParamResponse {
        
        public InsertWithParamResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWithParam", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWithParamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ParameterBytes;
        
        public UpdateWithParamRequest() {
        }
        
        public UpdateWithParamRequest(string tableName, byte[] ParameterBytes) {
            this.tableName = tableName;
            this.ParameterBytes = ParameterBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWithParamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWithParamResponse {
        
        public UpdateWithParamResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWithParam_2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWithParam_2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ParameterBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int keyNum;
        
        public UpdateWithParam_2Request() {
        }
        
        public UpdateWithParam_2Request(string tableName, byte[] ParameterBytes, int keyNum) {
            this.tableName = tableName;
            this.ParameterBytes = ParameterBytes;
            this.keyNum = keyNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWithParam_2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWithParam_2Response {
        
        public UpdateWithParam_2Response() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteStoredProcedure", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteStoredProcedureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ParameterBytes;
        
        public ExecuteStoredProcedureRequest() {
        }
        
        public ExecuteStoredProcedureRequest(string tableName, byte[] ParameterBytes) {
            this.tableName = tableName;
            this.ParameterBytes = ParameterBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteStoredProcedureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteStoredProcedureResponse {
        
        public ExecuteStoredProcedureResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DbWebSvcSoapChannel : RIIS.CarManager.DbWebSvc.DbWebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbWebSvcSoapClient : System.ServiceModel.ClientBase<RIIS.CarManager.DbWebSvc.DbWebSvcSoap>, RIIS.CarManager.DbWebSvc.DbWebSvcSoap {
        
        public DbWebSvcSoapClient() {
        }
        
        public DbWebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbWebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbWebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbWebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataFromSql(string strSql) {
            return base.Channel.GetDataFromSql(strSql);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataFromSqlAsync(string strSql) {
            return base.Channel.GetDataFromSqlAsync(strSql);
        }
        
        public void ExecuteSql(string strSql) {
            base.Channel.ExecuteSql(strSql);
        }
        
        public System.Threading.Tasks.Task ExecuteSqlAsync(string strSql) {
            return base.Channel.ExecuteSqlAsync(strSql);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RIIS.CarManager.DbWebSvc.InsertWithParamResponse RIIS.CarManager.DbWebSvc.DbWebSvcSoap.InsertWithParam(RIIS.CarManager.DbWebSvc.InsertWithParamRequest request) {
            return base.Channel.InsertWithParam(request);
        }
        
        public void InsertWithParam(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.InsertWithParamRequest inValue = new RIIS.CarManager.DbWebSvc.InsertWithParamRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            RIIS.CarManager.DbWebSvc.InsertWithParamResponse retVal = ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).InsertWithParam(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.InsertWithParamResponse> RIIS.CarManager.DbWebSvc.DbWebSvcSoap.InsertWithParamAsync(RIIS.CarManager.DbWebSvc.InsertWithParamRequest request) {
            return base.Channel.InsertWithParamAsync(request);
        }
        
        public System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.InsertWithParamResponse> InsertWithParamAsync(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.InsertWithParamRequest inValue = new RIIS.CarManager.DbWebSvc.InsertWithParamRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            return ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).InsertWithParamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RIIS.CarManager.DbWebSvc.UpdateWithParamResponse RIIS.CarManager.DbWebSvc.DbWebSvcSoap.UpdateWithParam(RIIS.CarManager.DbWebSvc.UpdateWithParamRequest request) {
            return base.Channel.UpdateWithParam(request);
        }
        
        public void UpdateWithParam(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.UpdateWithParamRequest inValue = new RIIS.CarManager.DbWebSvc.UpdateWithParamRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            RIIS.CarManager.DbWebSvc.UpdateWithParamResponse retVal = ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).UpdateWithParam(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParamResponse> RIIS.CarManager.DbWebSvc.DbWebSvcSoap.UpdateWithParamAsync(RIIS.CarManager.DbWebSvc.UpdateWithParamRequest request) {
            return base.Channel.UpdateWithParamAsync(request);
        }
        
        public System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParamResponse> UpdateWithParamAsync(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.UpdateWithParamRequest inValue = new RIIS.CarManager.DbWebSvc.UpdateWithParamRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            return ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).UpdateWithParamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response RIIS.CarManager.DbWebSvc.DbWebSvcSoap.UpdateWithParam_2(RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request request) {
            return base.Channel.UpdateWithParam_2(request);
        }
        
        public void UpdateWithParam_2(string tableName, byte[] ParameterBytes, int keyNum) {
            RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request inValue = new RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            inValue.keyNum = keyNum;
            RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response retVal = ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).UpdateWithParam_2(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response> RIIS.CarManager.DbWebSvc.DbWebSvcSoap.UpdateWithParam_2Async(RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request request) {
            return base.Channel.UpdateWithParam_2Async(request);
        }
        
        public System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.UpdateWithParam_2Response> UpdateWithParam_2Async(string tableName, byte[] ParameterBytes, int keyNum) {
            RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request inValue = new RIIS.CarManager.DbWebSvc.UpdateWithParam_2Request();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            inValue.keyNum = keyNum;
            return ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).UpdateWithParam_2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse RIIS.CarManager.DbWebSvc.DbWebSvcSoap.ExecuteStoredProcedure(RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest request) {
            return base.Channel.ExecuteStoredProcedure(request);
        }
        
        public void ExecuteStoredProcedure(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest inValue = new RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse retVal = ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).ExecuteStoredProcedure(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse> RIIS.CarManager.DbWebSvc.DbWebSvcSoap.ExecuteStoredProcedureAsync(RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest request) {
            return base.Channel.ExecuteStoredProcedureAsync(request);
        }
        
        public System.Threading.Tasks.Task<RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureResponse> ExecuteStoredProcedureAsync(string tableName, byte[] ParameterBytes) {
            RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest inValue = new RIIS.CarManager.DbWebSvc.ExecuteStoredProcedureRequest();
            inValue.tableName = tableName;
            inValue.ParameterBytes = ParameterBytes;
            return ((RIIS.CarManager.DbWebSvc.DbWebSvcSoap)(this)).ExecuteStoredProcedureAsync(inValue);
        }
        
        public System.Data.DataSet GetDataTables(string[] tableNameList) {
            return base.Channel.GetDataTables(tableNameList);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataTablesAsync(string[] tableNameList) {
            return base.Channel.GetDataTablesAsync(tableNameList);
        }
        
        public void ExecuteBatchSQL(string[] sqlArr) {
            base.Channel.ExecuteBatchSQL(sqlArr);
        }
        
        public System.Threading.Tasks.Task ExecuteBatchSQLAsync(string[] sqlArr) {
            return base.Channel.ExecuteBatchSQLAsync(sqlArr);
        }
    }
}
